project_id = "bzgkkwrnentbhrittkxa"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]

[functions.invite-driver]
verify_jwt = true
