import { supabase } from "../../shared/supabase-client.js";
import { mapRide, rideSelect } from "../../shared/services/ride-mapper.js";
export const MIN_TURNAROUND_MINUTES=30;
export const OPERATIONS_DATE=new Date().toISOString().slice(0,10);
const fail=e=>{if(e)throw e;};
const driverMap=p=>({id:p.id,name:`${p.first_name||""} ${p.last_name||""}`.trim(),shortName:p.first_name||"",email:p.email||"",phone:p.phone||"",photo:p.avatar_url||"",languages:p.driver_profiles?.[0]?.languages||[],availability:p.driver_profiles?.[0]?.availability_status||"offline",completedTrips:0,role:"Chauffeur"});
const vehicleMap=v=>({id:v.id,brand:v.brand,model:v.model,year:v.year,category:v.category,plate:v.plate||"Not provided",seats:v.seat_capacity||"—",luggageCapacity:v.luggage_capacity||"Not provided",image:v.image_url||"",status:v.operational_status,active:v.active,serviceDate:null,notes:""});
export async function getRideRequests(){const{data,error}=await supabase.from("rides").select(rideSelect).in("status",["request_received","under_review","offer_sent","declined"]).order("created_at",{ascending:false});fail(error);return(data||[]).map(mapRide);}
export async function getRequestById(id){return getJourneyById(id);}
export async function getJourneys(){const{data,error}=await supabase.from("rides").select(rideSelect).order("scheduled_start_at");fail(error);return(data||[]).map(mapRide);}
export async function getJourneyById(id){const{data,error}=await supabase.from("rides").select(rideSelect).eq("id",id).maybeSingle();fail(error);return mapRide(data);}
export async function getDrivers(){const{data,error}=await supabase.from("profiles").select("*,driver_profiles(*)").eq("role","driver").order("first_name");fail(error);return(data||[]).map(driverMap);}
export async function getVehicles(){const{data,error}=await supabase.from("vehicles").select("*").order("display_name");fail(error);return(data||[]).map(vehicleMap);}
export async function getPassengers(){const{data,error}=await supabase.from("profiles").select("*").eq("role","passenger").order("first_name");fail(error);return(data||[]).map(p=>({id:p.id,name:`${p.first_name} ${p.last_name}`.trim(),email:p.email||"",phone:p.phone||"",preferences:[],internalNotes:"",completedRides:0,upcomingRides:0,totalSpend:0,lastRide:null}));}
export async function getNotifications(){const{data,error}=await supabase.from("notifications").select("*").order("created_at",{ascending:false}).limit(50);fail(error);return(data||[]).map(n=>({id:n.id,title:n.title,body:n.message,createdAt:n.created_at,read:!!n.read_at,rideId:n.ride_id}));}
export async function getDriverApplications(){const{data,error}=await supabase.from("driver_applications").select("*,profile:profiles!driver_applications_user_id_fkey(*)").order("created_at",{ascending:false});fail(error);return data||[];}
export async function reviewDriverApplication(id,decision,note=""){const{error}=await supabase.rpc("admin_review_driver_application",{application_id:id,decision,note});fail(error);}
export async function inviteDriver(input){const{data,error}=await supabase.functions.invoke("invite-driver",{body:{email:input.email,firstName:input.firstName,lastName:input.lastName}});fail(error);if(data?.error)throw new Error(data.error);return data;}
export async function getAdminDashboard(){const[journeys,requests,drivers,vehicles]=await Promise.all([getJourneys(),getRideRequests(),getDrivers(),getVehicles()]);const today=journeys.filter(r=>r.pickupDate===OPERATIONS_DATE),unassigned=journeys.filter(r=>!["completed","cancelled","declined"].includes(r.status)&&(!r.driverId||!r.vehicleId));const alerts=[...unassigned.map(r=>({id:`assign-${r.id}`,severity:"critical",title:"Journey needs assignment",message:`${r.pickupTime} ${r.pickup.name} to ${r.destination.name}`,action:"Assign",href:`journeys/detail.html?id=${r.id}`})),...requests.filter(r=>["request_received","under_review"].includes(r.status)).map(r=>({id:`request-${r.id}`,severity:"warning",title:"New request waiting",message:`${r.passenger?.name}: ${r.pickup.name} to ${r.destination.name}`,action:"Review",href:`requests/?id=${r.id}`}))];return{date:OPERATIONS_DATE,today,requests,unassigned,alerts,metrics:{todayJourneys:today.length,newRequests:requests.filter(r=>["request_received","under_review"].includes(r.status)).length,unassignedRides:unassigned.length,driversAvailable:drivers.filter(d=>d.availability==="available").length,vehiclesAvailable:vehicles.filter(v=>v.status==="available").length}};}
export async function markRequestUnderReview(id){const{error}=await supabase.rpc("admin_update_ride",{p_ride:id,p_status:"under_review",p_payment:null});fail(error);return getJourneyById(id);}
export async function updateRidePrice(id,price,note=""){return sendRideOffer(id,price,note);}
export async function sendRideOffer(id,price,note=""){const{error}=await supabase.rpc("admin_send_offer",{ride_id:id,final_price:Number(price),note});fail(error);return getJourneyById(id);}
export async function declineRideRequest(id){const{error}=await supabase.rpc("admin_update_ride",{p_ride:id,p_status:"declined",p_payment:null});fail(error);return getJourneyById(id);}
export async function approveRideRequest(id){const{error}=await supabase.rpc("admin_update_ride",{p_ride:id,p_status:"confirmed",p_payment:null});fail(error);return getJourneyById(id);}
export async function checkDriverConflict(driverId,ride,exclude=ride?.id){if(!driverId)return{level:"available",message:"Available"};const{data,error}=await supabase.rpc("check_driver_conflict",{p_driver:driverId,p_start:new Date(`${ride.pickupDate}T${ride.pickupTime}`).toISOString(),p_end:ride.estimatedEndAt||new Date(new Date(`${ride.pickupDate}T${ride.pickupTime}`).getTime()+5400000).toISOString(),p_exclude:exclude});fail(error);return data?{level:"conflict",message:"Driver has an overlapping journey, unavailability, or insufficient 30-minute turnaround"}:{level:"available",message:"No conflicts"};}
export async function checkVehicleConflict(vehicleId,ride,exclude=ride?.id){if(!vehicleId)return{level:"available",message:"Available"};const{data,error}=await supabase.rpc("check_vehicle_conflict",{p_vehicle:vehicleId,p_start:new Date(`${ride.pickupDate}T${ride.pickupTime}`).toISOString(),p_end:ride.estimatedEndAt||new Date(new Date(`${ride.pickupDate}T${ride.pickupTime}`).getTime()+5400000).toISOString(),p_exclude:exclude});fail(error);return data?{level:"conflict",message:"Vehicle has an overlapping journey, unavailability, or insufficient 30-minute turnaround"}:{level:"available",message:"No conflicts"};}
export async function assignDriver(rideId,driverId){const{error}=await supabase.rpc("admin_assign_ride",{p_ride:rideId,p_driver:driverId||null,p_vehicle:null});fail(error);return getJourneyById(rideId);}
export async function assignVehicle(rideId,vehicleId){const{error}=await supabase.rpc("admin_assign_ride",{p_ride:rideId,p_driver:null,p_vehicle:vehicleId||null});fail(error);return getJourneyById(rideId);}
export async function updateJourneyStatus(id,status){const{error}=await supabase.rpc("admin_update_ride",{p_ride:id,p_status:status,p_payment:null});fail(error);return getJourneyById(id);}
export async function updatePaymentStatus(id,payment){const{error}=await supabase.rpc("admin_update_ride",{p_ride:id,p_status:null,p_payment:payment});fail(error);return getJourneyById(id);}
export async function updateJourneyNotes(id,notes){const entries=Object.entries(notes).filter(([,v])=>String(v||"").trim());if(!entries.length)return getJourneyById(id);const{data:{user}}=await supabase.auth.getUser();const rows=entries.map(([key,value])=>({ride_id:id,author_id:user.id,visibility:key==="internalNote"?"internal_admin":key==="driverNote"?"driver":"passenger",note:String(value)}));const{error}=await supabase.from("ride_notes").insert(rows);fail(error);return getJourneyById(id);}
export async function createManualRide(input){const passengers=await getPassengers(),p=input.passengerId?passengers.find(x=>x.id===input.passengerId):null;if(input.passengerId&&!p)throw new Error("Passenger not found");if(!p&&(!input.customerName?.trim()||!input.customerEmail?.trim()||!input.customerPhone?.trim()))throw new Error("Guest name, email and phone are required when no passenger is selected");const start=new Date(`${input.pickupDate}T${input.pickupTime}:00`);const payload={service_type:input.serviceType||"transfer",passenger_id:p?.id||null,customer_name:p?.name||input.customerName.trim(),customer_email:p?.email||input.customerEmail.trim(),customer_phone:p?.phone||input.customerPhone.trim(),pickup_name:input.pickup,pickup_address:input.pickup,destination_name:input.destination,destination_address:input.destination,scheduled_start_at:start.toISOString(),scheduled_end_at:new Date(start.getTime()+5400000).toISOString(),passenger_count:Number(input.passengers||1),luggage:input.luggage,flight_number:input.flightNumber,driver_id:input.driverId,vehicle_id:input.vehicleId,final_price:Number(input.price||0),currency:"CHF",booking_source:input.source||"admin",special_requests:input.specialRequests};const{data,error}=await supabase.rpc("admin_create_ride",{payload});fail(error);return getJourneyById(data);}
export async function setDriverUnavailable(id,p){const{data,error}=await supabase.from("driver_unavailability").insert({driver_id:id,starts_at:new Date(p.from).toISOString(),ends_at:new Date(p.to).toISOString(),reason:p.reason||"unavailable",notes:p.notes}).select().single();fail(error);return data;}
export async function setVehicleUnavailable(id,p){const{data,error}=await supabase.from("vehicle_unavailability").insert({vehicle_id:id,starts_at:new Date(p.from).toISOString(),ends_at:new Date(p.to).toISOString(),reason:p.reason||"other",notes:p.notes}).select().single();fail(error);return data;}
export async function resetAdminDemo(){return true;}
export function subscribeToAdminRides(onChange){const c=supabase.channel("admin-rides").on("postgres_changes",{event:"*",schema:"public",table:"rides"},onChange).subscribe();return()=>supabase.removeChannel(c);}
